package wappalyzer

var CategoryMap = map[string]string{
	"CMS":                             "product",
	"Message boards":                  "product",
	"Database managers":               "product",
	"Documentation":                   "product",
	"Widgets":                         "product",
	"Ecommerce":                       "product",
	"Photo galleries":                 "product",
	"Wikis":                           "product",
	"Hosting panels":                  "product",
	"Analytics":                       "product",
	"Blogs":                           "product",
	"JavaScript frameworks":           "webFramework",
	"Issue trackers":                  "product",
	"Video players":                   "product",
	"Comment systems":                 "product",
	"Security":                        "product",
	"Font scripts":                    "product",
	"Web frameworks":                  "framework",
	"Miscellaneous":                   "product",
	"Editors":                         "product",
	"LMS":                             "product",
	"Web servers":                     "webContainer",
	"Caching":                         "product",
	"Rich text editors":               "product",
	"JavaScript graphics":             "product",
	"Mobile frameworks":               "product",
	"Programming languages":           "programmingLanguage",
	"Operating systems":               "operatingSystem",
	"Search engines":                  "product",
	"Webmail":                         "product",
	"CDN":                             "product",
	"Marketing automation":            "product",
	"Web server extensions":           "product",
	"Databases":                       "product",
	"Maps":                            "product",
	"Advertising":                     "product",
	"Network devices":                 "product",
	"Media servers":                   "product",
	"Webcams":                         "product",
	"Payment processors":              "product",
	"Tag managers":                    "product",
	"CI":                              "product",
	"Control systems":                 "product",
	"Remote access":                   "product",
	"Development":                     "product",
	"Network storage":                 "product",
	"Feed readers":                    "product",
	"DMS":                             "product",
	"Page builders":                   "product",
	"Live chat":                       "product",
	"CRM":                             "product",
	"SEO":                             "product",
	"Accounting":                      "product",
	"Cryptominers":                    "product",
	"Static site generator":           "product",
	"User onboarding":                 "product",
	"JavaScript libraries":            "product",
	"Containers":                      "product",
	"PaaS":                            "product",
	"IaaS":                            "product",
	"Reverse proxies":                 "product",
	"Load balancers":                  "product",
	"UI frameworks":                   "framework",
	"Cookie compliance":               "product",
	"Accessibility":                   "product",
	"Social logins":                   "product",
	"SSL/TLS certificate authorities": "product",
	"Affiliate programs":              "product",
	"Appointment scheduling":          "product",
	"Surveys":                         "product",
	"A/B Testing":                     "product",
	"Email":                           "product",
	"Personalisation":                 "product",
	"Retargeting":                     "product",
	"RUM":                             "product",
	"Geolocation":                     "product",
	"WordPress themes":                "product",
	"Shopify themes":                  "product",
	"Drupal themes":                   "product",
	"Browser fingerprinting":          "product",
	"product":                         "product",
}
